INSERT INTO `GYMNASIUM`.`BLOG` (`ID`, `TITLE`, `IMAGE`, `CONTENT`, `TIMESTAMP`, `WRITER`) VALUES
('1', 'Today Is The Best Day To Starting Training. No Excuses', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog6_1024x1024.png?v=1639709323', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 15:18:25', '-- FirmFit--'),
('2', 'Fitness is not about being better than someone else', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog5_1024x1024.png?v=1639709301', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 22:34:55', '-- FirmFit--'),
('3', 'What Happend at the rx-fitness Chalenge Last Weekend', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog3_553c7cb8-982a-4e28-a694-2d2a42e9adb0_1024x1024.png?v=1639709275', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 22:34:55', '-- FirmFit--'),
('4', 'How to exercise effectively', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog4_b28dfcca-2a30-4325-824a-02c86a38381f_1024x1024.png?v=1639709240', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 22:34:55', '-- FirmFit--'),
('5', 'How to know enough or not?', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog2_f0c4728c-b443-49dd-9abd-44773eb908d4_1024x1024.png?v=1639709221', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 22:34:55', '-- FirmFit--'),
('6', 'Diet when exercising weight loss, science for women', 'https://cdn.shopify.com/s/files/1/0554/5784/1199/articles/blog1_0d29b473-654a-48d5-902d-1ecdfc32efdf_1024x1024.png?v=1639709165', 'Our gyms are designed and maintained to the highest standards, with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
<br/> <br/>
Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/>  <br/>
Quisque mattis, ligula id sodales ullamcorper, urna sem placerat lacus, id laoreet lectus sapien quis nisl. Phasellus eu massa id leo consectetur vehicula. Donec quis finibus lacus, id accumsan magna. Etiam ullamcorper id quam vitae iaculis.', '2022-03-09 22:34:55', '-- FirmFit--');