CREATE SCHEMA GYMNASIUM;
USE GYMNASIUM;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(320),
    PASSWORD VARCHAR(255),
    USERNAME VARCHAR(50),
    PHONENUM VARCHAR(20),
    ADDRESS VARCHAR(150),
    IMAGE TEXT,
    PERMISSION INT CHECK (PERMISSION = 0 OR PERMISSION = 1 OR PERMISSION = -1)
);

CREATE TABLE ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,
	PRODUCT_NAMES VARCHAR(255),
	STATUS_O VARCHAR(255),
	TOTAL VARCHAR(255),
	CREATED VARCHAR(255)
);

CREATE TABLE PAYMENTINFO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,
    NUMBER VARCHAR(50),
    EXPIRY_DATE DATETIME,
    UNIQUE (USERID, NUMBER),
    FOREIGN KEY (USERID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PRODUCT(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    TYPE INT CHECK (TYPE = 1 OR TYPE = 2),
    DESCRIPTION TEXT
);

CREATE TABLE PRODUCTIMAGE(
	ID INT,
    IMAGE VARCHAR(255),
    PRIMARY KEY (ID, IMAGE),
    FOREIGN KEY (ID) REFERENCES PRODUCT(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PRODUCTCATEGORY(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCTID INT,
    CATEGORY VARCHAR(20),
    PRICE INT,
    QUANTITY INT,
    UNIQUE (PRODUCTID, CATEGORY),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ORDERBILL(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,
    TIMESTAMP DATETIME,
    PHONENUM VARCHAR(20),
    ADDRESS VARCHAR(150), 
    PAYMENT_METHOD INT CHECK (PAYMENT_METHOD=1 OR PAYMENT_METHOD=2 OR PAYMENT_METHOD=3),
    UNIQUE (USERID, TIMESTAMP),
    FOREIGN KEY (USERID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ORDERITEM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ORDERID INT,
    CATEGORYID INT,
    QUANTITY INT,
    UNIQUE (ORDERID, CATEGORYID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERBILL(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (CATEGORYID) REFERENCES PRODUCTCATEGORY(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE FEEDBACK(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT,
    PRODUCTID INT ,
    TIMESTAMP DATETIME,
    RATING INT CHECK (RATING >= 1 AND RATING <= 5),
    CONTENT TEXT,
    UNIQUE (USERID, PRODUCTID, TIMESTAMP),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (USERID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE BLOG(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    IMAGE TEXT,
    CONTENT TEXT,
    TIMESTAMP DATETIME,
    WRITER VARCHAR(50),
);

CREATE TABLE EVENTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    IMAGE TEXT,
    CONTENT TEXT,
    TIMESTAMP DATETIME,
    WRITER VARCHAR(50)
);